---
# The format of this file is documented here:
# https://github.com/langchain4j/langchain4j-github-bot
features: [TRIAGE_ISSUES_AND_PULL_REQUESTS]
triage:
  rules:
    - id: azure
      labels: [Azure]
      title: "azure"
      notify: [jdubois, agoncal]
      notifyInPullRequest: true
      files:
        - '*-azure-*/**'
    - id: gemini
      labels: [Gemini]
      title: "gemini|vertex"
      notify: [glaforge]
      notifyInPullRequest: true
      files:
        - '*-vertex-*/**'
    - id: elasticsearch
      labels: [Elasticsearch]
      title: "elasticsearch"
      notify: [dadoonet]
      notifyInPullRequest: true
      files:
        - '*-elasticsearch-*/**'
