---
# The format of this file is documented here:
# https://github.com/langchain4j/langchain4j-github-bot
features: [TRIAGE_ISSUES_AND_PULL_REQUESTS]
triage:
  rules:
    - id: azure
      labels: [Azure]
      title: "azure"
      notify: [jdubois, agoncal]
      notifyInPullRequest: true
      files:
        - '*-azure-*/**'
    - id: gemini
      labels: [Gemini]
      title: "gemini|vertex|google"
      notify: [glaforge]
      notifyInPullRequest: true
      files:
        - '*-vertex-*/**'
        - '*-google-*/**'
    - id: elasticsearch
      labels: [Elasticsearch]
      title: "elasticsearch"
      notify: [dadoonet]
      notifyInPullRequest: true
      files:
        - 'langchain4j-elasticsearch/**'
    - id: mistral
      labels: [Mistral]
      title: "mistral"
      notify: [czelabueno]
      notifyInPullRequest: true
      files:
        - 'langchain4j-mistral-ai/**'
    - id: mcp
      labels: [MCP]
      title: "mcp"
      notify: [jmartisk]
      notifyInPullRequest: true
      files:
        - 'langchain4j-mcp/**'
