package dev.langchain4j.model.anthropic.internal.client;

import static dev.langchain4j.http.client.HttpMethod.DELETE;
import static dev.langchain4j.http.client.HttpMethod.GET;
import static dev.langchain4j.http.client.HttpMethod.POST;
import static dev.langchain4j.internal.Utils.getOrDefault;
import static dev.langchain4j.internal.ValidationUtils.ensureNotBlank;
import static dev.langchain4j.model.anthropic.internal.client.Json.fromJson;

import dev.langchain4j.Experimental;
import dev.langchain4j.http.client.HttpClient;
import dev.langchain4j.http.client.HttpClientBuilder;
import dev.langchain4j.http.client.HttpClientBuilderLoader;
import dev.langchain4j.http.client.HttpRequest;
import dev.langchain4j.http.client.SuccessfulHttpResponse;
import dev.langchain4j.http.client.log.LoggingHttpClient;
import dev.langchain4j.model.anthropic.internal.api.AnthropicFile;
import dev.langchain4j.model.anthropic.internal.api.AnthropicFileDeleteResponse;
import dev.langchain4j.model.anthropic.internal.api.AnthropicFilesListResponse;
import java.time.Duration;
import java.util.Collections;
import java.util.Map;
import java.util.function.Supplier;
import org.slf4j.Logger;

/**
 * Client for the Anthropic Files API ({@code /v1/files}), used to retrieve files generated by
 * Anthropic-managed Skills running inside the code execution container (see
 * {@link dev.langchain4j.model.anthropic.AnthropicSkill}).
 * <p>
 * All requests are sent with the {@code files-api-2025-04-14} beta header. Generated files are
 * only retrievable for 24 hours after creation.
 * <p>
 * Note: downloading the raw file content ({@code GET /v1/files/{file_id}/content}) is not yet
 * supported, since the shared {@link HttpClient} abstraction only exposes {@code String} request/
 * response bodies, which would corrupt binary content (e.g. {@code .xlsx}, {@code .pptx},
 * {@code .pdf}) on decode.
 *
 * @since 1.18.0
 */
@Experimental
public class AnthropicFilesClient {

    private static final String FILES_BETA = "files-api-2025-04-14";

    private final HttpClient httpClient;
    private final String baseUrl;
    private final String apiKey;
    private final String version;
    private final String beta;
    private final Supplier<Map<String, String>> customHeadersSupplier;

    public static Builder builder() {
        return new Builder();
    }

    AnthropicFilesClient(Builder builder) {
        HttpClientBuilder httpClientBuilder =
                getOrDefault(builder.httpClientBuilder, HttpClientBuilderLoader::loadHttpClientBuilder);

        HttpClient httpClient = httpClientBuilder
                .connectTimeout(getOrDefault(
                        getOrDefault(builder.timeout, httpClientBuilder.connectTimeout()), Duration.ofSeconds(15)))
                .readTimeout(getOrDefault(
                        getOrDefault(builder.timeout, httpClientBuilder.readTimeout()), Duration.ofSeconds(60)))
                .build();

        if (builder.logRequests != null && builder.logRequests
                || builder.logResponses != null && builder.logResponses) {
            this.httpClient =
                    new LoggingHttpClient(httpClient, builder.logRequests, builder.logResponses, builder.logger);
        } else {
            this.httpClient = httpClient;
        }

        this.baseUrl = ensureNotBlank(builder.baseUrl, "baseUrl");
        this.apiKey = ensureNotBlank(builder.apiKey, "apiKey");
        this.version = ensureNotBlank(builder.version, "version");
        this.beta = getOrDefault(builder.beta, FILES_BETA);
        this.customHeadersSupplier =
                builder.customHeadersSupplier != null ? builder.customHeadersSupplier : Collections::emptyMap;
    }

    /**
     * Uploads a file to the Anthropic Files API.
     *
     * @param filename the name of the file
     * @param mimeType the MIME type of the file content
     * @param content  the raw file content
     * @return metadata of the uploaded file
     */
    public AnthropicFile upload(String filename, String mimeType, byte[] content) {
        HttpRequest httpRequest = HttpRequest.builder()
                .method(POST)
                .url(baseUrl, "files")
                .addHeader("Content-Type", "multipart/form-data; boundary=----LangChain4j")
                .addHeader("x-api-key", apiKey)
                .addHeader("anthropic-version", version)
                .addHeader("anthropic-beta", beta)
                .addHeaders(customHeadersSupplier.get())
                .addFormDataFile("file", filename, mimeType, content)
                .build();

        SuccessfulHttpResponse response = httpClient.execute(httpRequest);
        return fromJson(response.body(), AnthropicFile.class);
    }

    /**
     * Retrieves metadata for a previously uploaded or generated file.
     *
     * @param fileId the file identifier (e.g. {@code "file_011CNvqeKgZx9CDdLYS8aUkV"})
     * @return metadata of the file
     */
    public AnthropicFile retrieve(String fileId) {
        SuccessfulHttpResponse response = httpClient.execute(toGetRequest("files/" + fileId));
        return fromJson(response.body(), AnthropicFile.class);
    }

    /**
     * Lists files, most recently created first.
     */
    public AnthropicFilesListResponse list() {
        SuccessfulHttpResponse response = httpClient.execute(toGetRequest("files"));
        return fromJson(response.body(), AnthropicFilesListResponse.class);
    }

    /**
     * Deletes a file.
     *
     * @param fileId the file identifier
     * @return confirmation of the deletion
     */
    public AnthropicFileDeleteResponse delete(String fileId) {
        HttpRequest httpRequest = HttpRequest.builder()
                .method(DELETE)
                .url(baseUrl, "files/" + fileId)
                .addHeader("x-api-key", apiKey)
                .addHeader("anthropic-version", version)
                .addHeader("anthropic-beta", beta)
                .addHeaders(customHeadersSupplier.get())
                .build();

        SuccessfulHttpResponse response = httpClient.execute(httpRequest);
        return fromJson(response.body(), AnthropicFileDeleteResponse.class);
    }

    /**
     * Downloads the raw content of a file.
     *
     * <p><b>Not yet supported:</b> the shared {@link HttpClient} abstraction only exposes
     * {@code String} response bodies, which would corrupt binary file content (e.g. {@code .xlsx},
     * {@code .pptx}, {@code .pdf}) on decode. Implementing this safely requires either a byte-array
     * response variant on the core {@link HttpClient} API, or bypassing this abstraction entirely.
     *
     * @param fileId the file identifier
     * @throws UnsupportedOperationException always, until binary-safe downloads are supported
     */
    public byte[] download(String fileId) {
        throw new UnsupportedOperationException(
                "Downloading raw file content is not yet supported: the shared HttpClient abstraction "
                        + "only exposes String response bodies, which would corrupt binary file content. "
                        + "See AnthropicFilesClient#download javadoc.");
    }

    private HttpRequest toGetRequest(String path) {
        return HttpRequest.builder()
                .method(GET)
                .url(baseUrl, path)
                .addHeader("x-api-key", apiKey)
                .addHeader("anthropic-version", version)
                .addHeader("anthropic-beta", beta)
                .addHeaders(customHeadersSupplier.get())
                .build();
    }

    public static class Builder {

        private HttpClientBuilder httpClientBuilder;
        private String baseUrl;
        private String apiKey;
        private String version;
        private String beta;
        private Duration timeout;
        private Logger logger;
        private Boolean logRequests;
        private Boolean logResponses;
        private Supplier<Map<String, String>> customHeadersSupplier;

        public Builder httpClientBuilder(HttpClientBuilder httpClientBuilder) {
            this.httpClientBuilder = httpClientBuilder;
            return this;
        }

        public Builder baseUrl(String baseUrl) {
            this.baseUrl = baseUrl;
            return this;
        }

        public Builder apiKey(String apiKey) {
            this.apiKey = apiKey;
            return this;
        }

        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Overrides the {@code anthropic-beta} header value. Defaults to {@code "files-api-2025-04-14"}.
         */
        public Builder beta(String beta) {
            this.beta = beta;
            return this;
        }

        public Builder timeout(Duration timeout) {
            this.timeout = timeout;
            return this;
        }

        public Builder logRequests(Boolean logRequests) {
            this.logRequests = logRequests;
            return this;
        }

        public Builder logResponses(Boolean logResponses) {
            this.logResponses = logResponses;
            return this;
        }

        public Builder logger(Logger logger) {
            this.logger = logger;
            return this;
        }

        public Builder customHeaders(Supplier<Map<String, String>> customHeadersSupplier) {
            this.customHeadersSupplier = customHeadersSupplier;
            return this;
        }

        public AnthropicFilesClient build() {
            return new AnthropicFilesClient(this);
        }
    }
}
