package dev.langchain4j.model;

import dev.langchain4j.model.output.Result;

public interface StreamingResponseHandler<T> {

    /**
     * This method is invoked each time language model generates a new token.
     *
     * @param token The new token, a part of a complete response
     */
    void onNext(String token);

    /**
     * This method is invoked once language model has finished streaming a response.
     *
     * @param result The complete result generated by a language model
     */
    default void onComplete(Result<T> result) {
    }

    /**
     * This method is invoked when an error occurs during streaming.
     *
     * @param error The error that occurred
     */
    void onError(Throwable error);
}
