#!/bin/bash
docker build --push --platform=linux/amd64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}_amd64 .
docker build --push --platform=linux/arm64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}_arm64 .
docker manifest create ${IMAGE_NAME} --amend ${IMAGE_NAME}_amd64 --amend ${IMAGE_NAME}_arm64
docker manifest push ${IMAGE_NAME}