package dev.langchain4j.store.embedding.oracle.vecdb;

import com.github.dockerjava.api.model.Capability;
import com.github.dockerjava.api.model.Device;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import javax.sql.DataSource;
import oracle.ucp.jdbc.PoolDataSource;
import oracle.ucp.jdbc.PoolDataSourceFactory;
import org.testcontainers.containers.Container;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

/**
 * Owns the shared Oracle Autonomous AI Database Free container used by VecDB integration tests.
 *
 * <p>Docker discovery, image pulling, host selection, and port forwarding are delegated to Testcontainers. The JDBC
 * wallet is generated by the database container and copied into a temporary directory for the test JVM.
 */
final class VecDbTestContainer {

    private static final String IMAGE = "ghcr.io/oracle/adb-free:26.2.4.2-26ai";
    private static final String CONNECTION_FACTORY_CLASS = "oracle.jdbc.datasource.impl.OracleDataSource";
    private static final String DATABASE_NAME = "LANGCHAIN4J";
    private static final String ADMIN_PASSWORD = "Welcome_Vecdb_123";
    private static final String WALLET_PASSWORD = "Welcome_Vecdb_123";
    private static final String WALLET_CONTAINER_PATH = "/u01/app/oracle/wallets/tls_wallet";
    private static final int DATABASE_PORT = 1522;

    private static final GenericContainer<?> DATABASE = createContainer();

    private VecDbTestContainer() {}

    static PoolDataSource dataSource() {
        return DataSourceHolder.DATA_SOURCE;
    }

    private static GenericContainer<?> createContainer() {
        return new GenericContainer<>(DockerImageName.parse(IMAGE))
                .withEnv("WORKLOAD_TYPE", "ATP")
                .withEnv("DATABASE_NAME", DATABASE_NAME)
                .withEnv("ADMIN_PASSWORD", ADMIN_PASSWORD)
                .withEnv("WALLET_PASSWORD", WALLET_PASSWORD)
                .withEnv("ENABLE_ARCHIVE_LOG", "False")
                .withExposedPorts(DATABASE_PORT)
                .withCreateContainerCmdModifier(command -> command.getHostConfig()
                        .withCapAdd(Capability.SYS_ADMIN)
                        .withDevices(Device.parse("/dev/fuse:/dev/fuse:rwm")))
                .waitingFor(Wait.forHealthcheck().withStartupTimeout(Duration.ofMinutes(30)));
    }

    private static PoolDataSource startDatabase() {
        DATABASE.start();
        try {
            Path walletDirectory = Files.createTempDirectory("langchain4j-vecdb-wallet-");
            copyWallet(walletDirectory);
            pointWalletAtMappedPort(walletDirectory);
            configureJdbcWallet(walletDirectory);

            PoolDataSource dataSource = PoolDataSourceFactory.getPoolDataSource();
            dataSource.setConnectionFactoryClassName(CONNECTION_FACTORY_CLASS);
            dataSource.setURL("jdbc:oracle:thin:@langchain4j_low?TNS_ADMIN=" + walletDirectory.toAbsolutePath());
            dataSource.setUser("ADMIN");
            dataSource.setPassword(ADMIN_PASSWORD);
            dataSource.setInitialPoolSize(1);
            dataSource.setMinPoolSize(1);
            dataSource.setMaxPoolSize(5);
            awaitDatabase(dataSource);
            return dataSource;
        } catch (Exception exception) {
            DATABASE.stop();
            throw new IllegalStateException("Unable to initialize the VecDB test container", exception);
        }
    }

    private static void copyWallet(Path walletDirectory) throws Exception {
        Container.ExecResult walletFiles = DATABASE.execInContainer(
                "find", WALLET_CONTAINER_PATH, "-maxdepth", "1", "-type", "f", "-printf", "%f\n");
        if (walletFiles.getExitCode() != 0) {
            throw new IllegalStateException("Unable to list the generated ADB wallet: " + walletFiles.getStderr());
        }

        for (String fileName :
                walletFiles.getStdout().lines().filter(line -> !line.isBlank()).toList()) {
            DATABASE.copyFileFromContainer(
                    WALLET_CONTAINER_PATH + "/" + fileName,
                    walletDirectory.resolve(fileName).toString());
        }
    }

    private static void pointWalletAtMappedPort(Path walletDirectory) throws Exception {
        Path tnsNames = walletDirectory.resolve("tnsnames.ora");
        String configuredTnsNames = Files.readString(tnsNames)
                .replaceAll("(?i)(HOST\\s*=\\s*)[^)]+", "$1" + DATABASE.getHost())
                .replaceAll("(?i)(PORT\\s*=\\s*)" + DATABASE_PORT, "$1" + DATABASE.getMappedPort(DATABASE_PORT));
        Files.writeString(tnsNames, configuredTnsNames);
    }

    private static void configureJdbcWallet(Path walletDirectory) throws Exception {
        String wallet = walletDirectory.resolve("cwallet.sso").toAbsolutePath().toString();
        String jdbcProperties = """
                javax.net.ssl.keyStore=%s
                javax.net.ssl.keyStoreType=SSO
                javax.net.ssl.trustStore=%s
                javax.net.ssl.trustStoreType=SSO
                """.formatted(wallet, wallet);
        Files.writeString(walletDirectory.resolve("ojdbc.properties"), jdbcProperties);
    }

    private static void awaitDatabase(DataSource dataSource) throws Exception {
        long deadline = System.nanoTime() + Duration.ofMinutes(5).toNanos();
        SQLException lastFailure = null;

        while (System.nanoTime() < deadline) {
            try (Connection connection = dataSource.getConnection();
                    Statement statement = connection.createStatement();
                    ResultSet resultSet = statement.executeQuery("SELECT 1 FROM DUAL")) {
                if (resultSet.next()) {
                    return;
                }
            } catch (SQLException exception) {
                lastFailure = exception;
            }
            Thread.sleep(Duration.ofSeconds(5).toMillis());
        }

        throw new IllegalStateException("ADB container did not accept JDBC connections", lastFailure);
    }

    private static final class DataSourceHolder {

        private static final PoolDataSource DATA_SOURCE = startDatabase();
    }
}
