package dev.langchain4j.service.tool.search;

import dev.langchain4j.Experimental;
import dev.langchain4j.agent.tool.ToolSpecification;
import dev.langchain4j.invocation.InvocationContext;

import java.util.List;

/**
 * Strategy for discovering tools dynamically by an LLM during an AI Service invocation.
 * <p>
 * A {@code ToolSearchStrategy} allows reducing token usage by avoiding sending all available
 * tools to the LLM upfront. Instead, the LLM is initially exposed only to one or more
 * <em>tool search tools</em>, which it can call to discover relevant tools on demand.
 * <p>
 * Once the LLM performs a tool search, the matching tools are included in subsequent
 * requests, typically accumulating until the corresponding search result message is evicted
 * from the chat memory.
 * <p>
 * LangChain4j provides out-of-the-box implementations such as
 * {@link dev.langchain4j.service.tool.search.simple.SimpleToolSearchStrategy}
 * and {@link dev.langchain4j.service.tool.search.vector.VectorToolSearchStrategy},
 * but custom strategies can be implemented to support alternative discovery mechanisms.
 *
 * @see dev.langchain4j.service.tool.search.simple.SimpleToolSearchStrategy
 * @see dev.langchain4j.service.tool.search.vector.VectorToolSearchStrategy
 * @since 1.12.0
 */
@Experimental
public interface ToolSearchStrategy {

    /**
     * Returns one or more tool specifications that are exposed to the LLM and are used to perform tool searches.
     *
     * @param invocationContext the AI Service invocation context
     * @return list containing one or more tool search tools
     */
    List<ToolSpecification> getToolSearchTools(InvocationContext invocationContext);

    /**
     * Executes a tool search request generated by the LLM and matching it against searchable tools.
     *
     * @param toolSearchRequest the tool search request
     * @return the search result containing matching tool names
     */
    ToolSearchResult search(ToolSearchRequest toolSearchRequest);
}
