name: langchain4j-github-bot.yml lint

on:
  push:
    paths:
      - '.github/langchain4j-github-bot.yml'
  pull_request:
    paths:
      - '.github/langchain4j-github-bot.yml'

jobs:
  lint:
    name: "langchain4j-github-bot.yml validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install yamllint
        shell: bash
        run: sudo apt-get install -y yamllint
      - name: run yamllint for langchain4j-github-bot.yml
        shell: bash
        run: yamllint -c .github/yamllint.conf .github/langchain4j-github-bot.yml
