name: snapshot_release

on:
  repository_dispatch:
    types: [ trigger-snapshot-release ]
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: snapshot-release
  cancel-in-progress: false

jobs:
  snapshot_release:
    if: github.repository == 'langchain4j/langchain4j'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
        # Modules specify the oldest java version that they support:
        # even if we build with version 25, produced jars should be compatible with
        # JVMs running the version specified in each module's maven.compiler.target property
          java-version: '25'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD

      - name: snapshot_release
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          mvn -B -U --fail-at-end -DskipTests -DskipITs clean deploy

      - name: Trigger SNAPSHOT release for langchain4j-spring repo
        if: ${{ github.event_name == 'repository_dispatch' }}
        env:
          GH_TOKEN: ${{ secrets.GH_RELEASE_AUTOMATION }}
        run: |
          gh api repos/langchain4j/langchain4j-spring/dispatches \
            -f event_type=trigger-snapshot-release
