name: snapshot_release_core_and_parent

# Only run on pushes to main:
# Replace with 'on: [push]' if you need to run tests on your PR
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  snapshot_release_core_and_parent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
        # Modules specify the oldest java version that they support:
        # even if we build with version 21, produced jars should be compatible with
        # JVMs running the version specified in each module's maven.compiler.target property
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: snapshot_release_core_and_parent
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        # Notes:
        #  - tests already run in a separate action (main)
        run: mvn -B -U --fail-at-end -DskipTests -DskipAnthropicITs -DskipLocalAiITs -DskipMilvusITs -DskipMongoDbAtlasITs -DskipOllamaITs -DskipVearchITs -DskipVertexAiGeminiITs -pl langchain4j-core,langchain4j-parent clean deploy
