name: Trigger docs build and Spring snapshot release

on:
  workflow_dispatch:

jobs:
  trigger:
    if: github.repository == 'langchain4j/langchain4j'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation build and deploy
        run: |
          gh api repos/langchain4j/langchain4j/dispatches \
            -f event_type=trigger-docs-build-and-deploy

      - name: Trigger SNAPSHOT release for langchain4j-spring repo
        run: |
          gh api repos/langchain4j/langchain4j-spring/dispatches \
            -f event_type=trigger-snapshot-release
