package dev.langchain4j.store.embedding.oracle.vecdb;

import static dev.langchain4j.internal.Utils.randomUUID;
import static dev.langchain4j.internal.ValidationUtils.ensureGreaterThanZero;
import static dev.langchain4j.internal.ValidationUtils.ensureNotBlank;
import static dev.langchain4j.internal.ValidationUtils.ensureNotNull;

import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.store.embedding.EmbeddingSearchRequest;
import dev.langchain4j.store.embedding.EmbeddingSearchResult;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.filter.Filter;
import dev.langchain4j.store.embedding.oracle.CreateOption;
import dev.langchain4j.store.embedding.oracle.SQLFilter;
import dev.langchain4j.store.embedding.oracle.SQLFilters;
import dev.langchain4j.store.embedding.oracle.vecdb.enums.VecDbDistanceMetric;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;

/**
 * A LangChain4j embedding store backed by {@code DBMS_VECTOR_DATABASE}.
 *
 * <p>The store uses bring-your-own vectors: embeddings are generated by a LangChain4j embedding model and persisted in
 * VecDB. Instances are immutable and safe to share between threads when the configured {@link DataSource} is
 * thread-safe.
 *
 * <p>The required store distance metric controls similarity search and score conversion. It is independent from the
 * vector-index metric. If they differ, Oracle bypasses the index and performs an exact search.
 */
public final class OracleVecDbEmbeddingStore implements EmbeddingStore<TextSegment> {

    private final DataSource dataSource;
    private final VecDbEmbeddingTable embeddingTable;
    private final VecDbQueryExecutor queryExecutor;
    private final VecDbDistanceMetric distanceMetric;

    private OracleVecDbEmbeddingStore(Builder builder) {
        this.dataSource = builder.dataSource;
        this.embeddingTable = builder.embeddingTable;
        this.queryExecutor = builder.queryExecutor;
        this.distanceMetric = builder.distanceMetric;

        VecDbSchemaManager schemaManager = new VecDbSchemaManager(queryExecutor);
        try (Connection connection = dataSource.getConnection()) {
            schemaManager.prepareSchema(
                    connection, embeddingTable, builder.index, builder.metadataIndex, builder.parallelCreation);
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    /** Returns a builder for an Oracle VecDB embedding store. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Describes the VecDB vector table configured for this store.
     *
     * @return the table name, optional comment, and annotations reported by
     *     {@code DBMS_VECTOR_DATABASE.DESCRIBE_VECTOR_TABLE}
     */
    public VectorTableDescription describeVectorTable() {
        try (Connection connection = dataSource.getConnection()) {
            String responseJson = queryExecutor.describeVectorTable(connection, embeddingTable.name());
            return VecDbEmbeddingTableJsonMapper.descriptionFromJson(responseJson);
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    @Override
    public String add(Embedding embedding) {
        ensureNotNull(embedding, "embedding");

        String id = randomUUID();
        upsert(VecDbVectorJsonMapper.toJson(Collections.singletonList(id), Collections.singletonList(embedding)));
        return id;
    }

    @Override
    public void add(String id, Embedding embedding) {
        ensureNotBlank(id, "id");
        ensureNotNull(embedding, "embedding");

        upsert(VecDbVectorJsonMapper.toJson(Collections.singletonList(id), Collections.singletonList(embedding)));
    }

    @Override
    public String add(Embedding embedding, TextSegment embedded) {
        ensureNotNull(embedding, "embedding");
        ensureNotNull(embedded, "embedded");

        String id = randomUUID();
        upsert(VecDbVectorJsonMapper.toJson(
                Collections.singletonList(id),
                Collections.singletonList(embedding),
                Collections.singletonList(embedded)));
        return id;
    }

    @Override
    public List<String> addAll(List<Embedding> embeddings) {
        ensureNotNull(embeddings, "embeddings");
        if (embeddings.isEmpty()) {
            return Collections.emptyList();
        }

        List<String> ids = generateIds(embeddings.size());
        upsert(VecDbVectorJsonMapper.toJson(ids, embeddings));
        return ids;
    }

    @Override
    public void addAll(List<String> ids, List<Embedding> embeddings, List<TextSegment> embedded) {
        String vectorsJson = VecDbVectorJsonMapper.toJson(ids, embeddings, embedded);
        if (ids.isEmpty()) {
            return;
        }
        upsert(vectorsJson);
    }

    @Override
    public void removeAll(Collection<String> ids) {
        String idsJson = VecDbVectorJsonMapper.idsToJson(ids);

        try (Connection connection = dataSource.getConnection()) {
            queryExecutor.deleteVectors(connection, embeddingTable.name(), idsJson);
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    @Override
    public void removeAll(Filter filter) {
        ensureNotNull(filter, "filter");
        VecDbFilters.validate(filter);
        SQLFilter sqlFilter = SQLFilters.create(filter, embeddingTable::mapMetadataKey);

        try (Connection connection = dataSource.getConnection()) {
            queryExecutor.deleteVectorsByFilter(connection, embeddingTable.name(), sqlFilter);
            if (!connection.getAutoCommit()) {
                connection.commit();
            }
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    @Override
    public void removeAll() {
        try (Connection connection = dataSource.getConnection()) {
            queryExecutor.truncateVectorTable(connection, embeddingTable.name());
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    @Override
    public EmbeddingSearchResult<TextSegment> search(EmbeddingSearchRequest request) {
        VecDbSearchRequestMapper.VecDbSearchParameters parameters =
                VecDbSearchRequestMapper.map(request, distanceMetric);

        try (Connection connection = dataSource.getConnection()) {
            String responseJson = queryExecutor.search(
                    connection,
                    embeddingTable.name(),
                    parameters.queryJson(),
                    parameters.filtersJson(),
                    parameters.maxResults(),
                    parameters.includeVectors(),
                    parameters.advancedOptionsJson());
            return VecDbSearchResultMapper.map(responseJson, request.minScore(), distanceMetric);
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    private void upsert(String vectorsJson) {
        try (Connection connection = dataSource.getConnection()) {
            queryExecutor.upsertVectors(connection, embeddingTable.name(), vectorsJson);
        } catch (SQLException exception) {
            throw unchecked(exception);
        }
    }

    private static RuntimeException unchecked(SQLException exception) {
        return new RuntimeException(exception);
    }

    /** Selected fields returned when describing a VecDB vector table. */
    public record VectorTableDescription(String tableName, String comment, Map<String, Object> annotations) {

        public VectorTableDescription {
            tableName = ensureNotBlank(tableName, "tableName");
            annotations = annotations == null ? Map.of() : Map.copyOf(annotations);
        }
    }

    /** Builder for {@link OracleVecDbEmbeddingStore}. */
    public static final class Builder {

        private DataSource dataSource;
        private VecDbEmbeddingTable embeddingTable;
        private VecDbVectorIndex index;
        private VecDbDistanceMetric distanceMetric;
        private VecDbMetadataIndex metadataIndex;
        private Integer parallelCreation;
        private VecDbQueryExecutor queryExecutor = new VecDbJdbcQueryExecutor();

        private Builder() {}

        /** Configures the data source used to obtain Oracle Database connections. */
        public Builder dataSource(DataSource dataSource) {
            this.dataSource = ensureNotNull(dataSource, "dataSource");
            return this;
        }

        /** Configures an existing VecDB vector table. */
        public Builder embeddingTable(String tableName) {
            return embeddingTable(tableName, CreateOption.CREATE_NONE);
        }

        /** Configures a VecDB vector table and its creation behavior. */
        public Builder embeddingTable(String tableName, CreateOption createOption) {
            return embeddingTable(VecDbEmbeddingTable.builder()
                    .name(ensureNotBlank(tableName, "tableName"))
                    .createOption(ensureNotNull(createOption, "createOption"))
                    .build());
        }

        /** Configures the VecDB vector table used by the store. */
        public Builder embeddingTable(VecDbEmbeddingTable embeddingTable) {
            this.embeddingTable = ensureNotNull(embeddingTable, "embeddingTable");
            return this;
        }

        /** Configures the vector index, including its independent index-time distance metric. */
        public Builder index(VecDbVectorIndex index) {
            this.index = ensureNotNull(index, "index");
            return this;
        }

        /**
         * Configures the distance metric used for VecDB searches and score conversion.
         *
         * <p>The metric is written to {@code advanced_options.distance_metric}. It is independent from
         * {@link VecDbIndexBuilder#distanceMetric(VecDbDistanceMetric)}, which configures the vector index. If the
         * values differ, Oracle cannot use that index and performs an exact search with this store metric.
         *
         * <p>Oracle's underlying metric-selection rules are:
         * <ul>
         *     <li>A search over one indexed vector column uses that index's metric.</li>
         *     <li>A search without a vector index uses cosine when no metric is specified.</li>
         *     <li>A query involving multiple indexed vector columns uses their metric only when all indexes share it;
         *     otherwise it uses cosine.</li>
         * </ul>
         *
         * <p>This store always supplies the configured search metric. An approximate index-based search requires its
         * value to match the vector-index metric.
         *
         * @param distanceMetric search-time distance metric
         * @return this builder
         * @throws IllegalArgumentException if {@code distanceMetric} is {@code null}
         * @see <a href="https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/vector_distance.html">
         *     Oracle VECTOR_DISTANCE metric-selection rules</a>
         */
        public Builder distanceMetric(VecDbDistanceMetric distanceMetric) {
            this.distanceMetric = ensureNotNull(distanceMetric, "distanceMetric");
            return this;
        }

        /** Configures the metadata index. */
        public Builder metadataIndex(VecDbMetadataIndex metadataIndex) {
            this.metadataIndex = ensureNotNull(metadataIndex, "metadataIndex");
            return this;
        }

        /** Configures the parallelism used when VecDB creates indexes. */
        public Builder parallelCreation(int parallelCreation) {
            this.parallelCreation = ensureGreaterThanZero(parallelCreation, "parallelCreation");
            return this;
        }

        Builder queryExecutor(VecDbQueryExecutor queryExecutor) {
            this.queryExecutor = ensureNotNull(queryExecutor, "queryExecutor");
            return this;
        }

        /** Creates the store and prepares its configured VecDB schema objects. */
        public OracleVecDbEmbeddingStore build() {
            ensureNotNull(dataSource, "dataSource");
            ensureNotNull(embeddingTable, "embeddingTable");
            ensureNotNull(distanceMetric, "distanceMetric");
            return new OracleVecDbEmbeddingStore(this);
        }
    }
}
