package dev.langchain4j.store.embedding.oracle.vecdb;

import static dev.langchain4j.internal.ValidationUtils.ensureNotBlank;
import static dev.langchain4j.internal.ValidationUtils.ensureNotNull;

import dev.langchain4j.store.embedding.oracle.CreateOption;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Configuration of a vector table managed by {@code DBMS_VECTOR_DATABASE}.
 *
 * <p>The first VecDB implementation uses bring-your-own vectors, so the vector type is always {@code dense} and IDs
 * are generated by LangChain4j rather than by the database.
 */
public final class VecDbEmbeddingTable {

    private final String name;
    private final String description;
    private final Map<String, Object> annotations;
    private final CreateOption createOption;

    private VecDbEmbeddingTable(Builder builder) {
        this.name = builder.name;
        this.description = builder.description;
        this.annotations = Map.copyOf(builder.annotations);
        this.createOption = builder.createOption;
    }

    /**
     * Returns a builder for a VecDB vector table.
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Returns the vector table name.
     */
    public String name() {
        return name;
    }

    /**
     * Returns the optional vector table description.
     */
    public String description() {
        return description;
    }

    /**
     * Returns the user-defined vector table annotations.
     */
    public Map<String, Object> annotations() {
        return annotations;
    }

    /**
     * Returns the option controlling whether the vector table is created.
     */
    public CreateOption createOption() {
        return createOption;
    }

    /**
     * Builder for {@link VecDbEmbeddingTable}.
     */
    public static final class Builder {

        private String name;
        private String description;
        private final Map<String, Object> annotations = new LinkedHashMap<>();
        private CreateOption createOption = CreateOption.CREATE_NONE;

        private Builder() {}

        /**
         * Configures the vector table name.
         */
        public Builder name(String name) {
            this.name = ensureNotBlank(name, "name");
            return this;
        }

        /**
         * Configures an optional description stored with the vector table.
         */
        public Builder description(String description) {
            this.description = ensureNotBlank(description, "description");
            return this;
        }

        /**
         * Adds a user-defined annotation stored with the vector table.
         */
        public Builder annotation(String name, Object value) {
            annotations.put(ensureNotBlank(name, "annotation name"), ensureNotNull(value, "annotation value"));
            return this;
        }

        /**
         * Configures whether the vector table should be created, reused, or replaced.
         */
        public Builder createOption(CreateOption createOption) {
            this.createOption = ensureNotNull(createOption, "createOption");
            return this;
        }

        /**
         * Builds the vector table configuration.
         */
        public VecDbEmbeddingTable build() {
            ensureNotBlank(name, "name");
            return new VecDbEmbeddingTable(this);
        }
    }
}
