package dev.langchain4j.model.anthropic;

import dev.langchain4j.Experimental;

/**
 * Anthropic-managed <a href="https://docs.anthropic.com/en/docs/agents-and-tools/agent-skills/overview">Agent Skills</a>
 * that let Claude generate real downloadable documents by running pre-built skills inside the code execution container.
 * <p>
 * Enable them via {@link AnthropicChatModel.AnthropicChatModelBuilder#skills(AnthropicSkill...)} or
 * {@link AnthropicStreamingChatModel.AnthropicStreamingChatModelBuilder#skills(AnthropicSkill...)}, which also
 * auto-enables the required {@code code_execution} server tool and beta headers.
 * <p>
 * Skills are supported on Claude Sonnet 4 / 4.5, Opus 4 and later. At most 8 skills may be enabled per request,
 * and files generated by skills are downloadable for 24 hours through Anthropic's Files API.
 *
 * @since 1.18.0
 */
@Experimental
public enum AnthropicSkill {

    /**
     * Generates Microsoft Excel spreadsheets ({@code .xlsx}).
     */
    XLSX("xlsx"),

    /**
     * Generates Microsoft PowerPoint presentations ({@code .pptx}).
     */
    PPTX("pptx"),

    /**
     * Generates Microsoft Word documents ({@code .docx}).
     */
    DOCX("docx"),

    /**
     * Generates PDF documents ({@code .pdf}).
     */
    PDF("pdf");

    private final String skillId;

    AnthropicSkill(String skillId) {
        this.skillId = skillId;
    }

    /**
     * The Anthropic skill identifier (e.g. {@code "xlsx"}) sent in the {@code container.skills} request block.
     */
    public String skillId() {
        return skillId;
    }
}
