package dev.langchain4j.model.anthropic;

import static dev.langchain4j.model.anthropic.internal.mapper.AnthropicMapper.SERVER_TOOL_RESULTS_KEY;

import dev.langchain4j.Experimental;
import dev.langchain4j.model.chat.response.ChatResponse;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Helper methods for working with files generated by Anthropic-managed {@link AnthropicSkill}s
 * running inside the code execution container.
 * <p>
 * Requires {@code returnServerToolResults(true)} to be set on the chat model, so that server tool
 * results (including {@code code_execution_tool_result} blocks) are surfaced on the {@link ChatResponse}.
 *
 * @since 1.18.0
 */
@Experimental
public final class AnthropicSkills {

    private AnthropicSkills() {}

    /**
     * Extracts the IDs of files generated by Skills/code execution during this response, in the
     * order they appear. Returns an empty list if no files were generated or
     * {@code returnServerToolResults(true)} was not set.
     * <p>
     * The resulting file IDs can be retrieved/downloaded via the Anthropic Files API within 24 hours
     * of generation.
     */
    public static List<String> extractFileIds(ChatResponse chatResponse) {
        Object rawResults = chatResponse.aiMessage().attributes().get(SERVER_TOOL_RESULTS_KEY);
        if (!(rawResults instanceof List<?> results)) {
            return List.of();
        }

        Set<String> fileIds = new LinkedHashSet<>();
        for (Object result : results) {
            if (result instanceof AnthropicServerToolResult serverToolResult) {
                collectFileIds(serverToolResult.content(), fileIds);
            }
        }
        return new ArrayList<>(fileIds);
    }

    private static void collectFileIds(Object node, Set<String> fileIds) {
        if (node instanceof Map<?, ?> map) {
            Object fileId = map.get("file_id");
            if (fileId instanceof String fileIdString) {
                fileIds.add(fileIdString);
            }
            map.values().forEach(value -> collectFileIds(value, fileIds));
        } else if (node instanceof List<?> list) {
            list.forEach(value -> collectFileIds(value, fileIds));
        }
    }
}
